apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    app.kubernetes.io/managed-by: helm
  name: externalsecrets.kubernetes-client.io
spec:
  group: kubernetes-client.io
  names:
    kind: ExternalSecret
    plural: externalsecrets
    shortNames:
    - es
    singular: externalsecret
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.lastSync
      name: Last Sync
      type: date
    - jsonPath: .status.status
      name: status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            anyOf:
            - required:
              - data
            - required:
              - dataFrom
            oneOf:
            - properties:
                backendType:
                  enum:
                  - secretsManager
                  - systemManager
            - properties:
                backendType:
                  enum:
                  - vault
            - properties:
                backendType:
                  enum:
                  - azureKeyVault
              required:
              - keyVaultName
            - properties:
                backendType:
                  enum:
                  - gcpSecretsManager
            - properties:
                backendType:
                  enum:
                  - alicloudSecretsManager
            - properties:
                backendType:
                  enum:
                  - ibmcloudSecretsManager
            - properties:
                backendType:
                  enum:
                  - akeyless
            properties:
              backendType:
                description: Determines which backend to use for fetching secrets
                enum:
                - secretsManager
                - systemManager
                - vault
                - azureKeyVault
                - gcpSecretsManager
                - alicloudSecretsManager
                - ibmcloudSecretsManager
                - akeyless
                type: string
              controllerId:
                description: The ID of controller instance that manages this ExternalSecret.
                  This is needed in case there is more than a KES controller instances
                  within the cluster.
                type: string
              data:
                items:
                  oneOf:
                  - required:
                    - key
                    - name
                  - required:
                    - path
                  properties:
                    isBinary:
                      description: Whether the backend secret shall be treated as
                        binary data represented by a base64-encoded string. You must
                        set this to true for any base64-encoded binary data in the
                        backend - to ensure it is not encoded in base64 again. Default
                        is false.
                      type: boolean
                    key:
                      description: Secret key in backend
                      type: string
                    name:
                      description: Name set for this key in the generated secret
                      type: string
                    path:
                      description: Path from SSM to scrape secrets This will fetch
                        all secrets and use the key from the secret as variable name
                      type: string
                    property:
                      description: Property to extract if secret in backend is a JSON
                        object
                      type: string
                    recursive:
                      description: Allow to recurse thru all child keys on a given
                        path, default false
                      type: boolean
                    secretType:
                      description: 'Used by: ibmcloudSecretsManager Type of secret
                        - one of username_password, iam_credentials or arbitrary'
                      type: string
                    version:
                      description: 'Used by: gcpSecretsManager'
                      type: string
                      x-kubernetes-int-or-string: true
                    versionId:
                      description: 'Used by: secretsManager'
                      type: string
                    versionStage:
                      description: 'Used by: alicloudSecretsManager, secretsManager'
                      type: string
                  type: object
                type: array
              dataFrom:
                items:
                  type: string
                type: array
              keyVaultName:
                description: 'Used by: azureKeyVault'
                type: string
              kvVersion:
                description: Vault K/V version either 1 or 2, default = 2
                maximum: 2
                minimum: 1
                type: integer
              projectId:
                description: 'Used by: gcpSecretsManager'
                type: string
              region:
                description: 'Used by: secretsManager, systemManager'
                type: string
              roleArn:
                description: 'Used by: alicloudSecretsManager, secretsManager, systemManager'
                type: string
              template:
                description: Template which will be deep merged without mutating any
                  existing fields. into generated secret, can be used to set for example
                  annotations or type on the generated secret
                type: object
                x-kubernetes-preserve-unknown-fields: true
              type:
                description: 'DEPRECATED: Use spec.template.type'
                type: string
              vaultMountPoint:
                description: 'Used by: vault'
                type: string
              vaultRole:
                description: 'Used by: vault'
                type: string
            type: object
          status:
            properties:
              lastSync:
                type: string
              observedGeneration:
                type: number
              status:
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-8.3.0
  name: external-secrets-kubernetes-external-secrets
  namespace: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-8.3.0
  name: external-secrets-kubernetes-external-secrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apiextensions.k8s.io
  resourceNames:
  - externalsecrets.kubernetes-client.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - update
- apiGroups:
  - kubernetes-client.io
  resources:
  - externalsecrets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - kubernetes-client.io
  resources:
  - externalsecrets/status
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-8.3.0
  name: external-secrets-kubernetes-external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-kubernetes-external-secrets
subjects:
- kind: ServiceAccount
  name: external-secrets-kubernetes-external-secrets
  namespace: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-8.3.0
  name: external-secrets-kubernetes-external-secrets-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: external-secrets-kubernetes-external-secrets
  namespace: external-secrets
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-8.3.0
  name: external-secrets-kubernetes-external-secrets
  namespace: external-secrets
spec:
  ports:
  - name: prometheus
    port: 3001
    protocol: TCP
    targetPort: prometheus
  selector:
    app.kubernetes.io/name: kubernetes-external-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-8.3.0
  name: external-secrets-kubernetes-external-secrets
  namespace: external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/name: kubernetes-external-secrets
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: external-secrets
        app.kubernetes.io/name: kubernetes-external-secrets
    spec:
      containers:
      - env:
        - name: AKEYLESS_API_ENDPOINT
          value: https://api.akeyless.io
        - name: AWS_DEFAULT_REGION
          value: us-west-2
        - name: AWS_REGION
          value: us-west-2
        - name: LOG_LEVEL
          value: info
        - name: LOG_MESSAGE_KEY
          value: msg
        - name: METRICS_PORT
          value: "3001"
        - name: POLLER_INTERVAL_MILLISECONDS
          value: "10000"
        - name: VAULT_ADDR
          value: http://127.0.0.1:8200
        - name: WATCH_TIMEOUT
          value: "60000"
        image: ghcr.io/external-secrets/kubernetes-external-secrets:8.3.0
        imagePullPolicy: IfNotPresent
        name: kubernetes-external-secrets
        ports:
        - containerPort: 3001
          name: prometheus
        resources: {}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: external-secrets-kubernetes-external-secrets
